version: '3'

volumes:
  database:

networks:
  database:

x-env_file:
  &env_file
  - ./.env

services:
  database:
    container_name: plusmoney_database
    image: mysql:8.0
    env_file:
      *env_file
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - database

  app:
    container_name: plusmoney_app
    image: node:14.17-alpine
    env_file:
      *env_file
    volumes:
      - ./:/home/app
    working_dir: /home/app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    depends_on: 
      - database
    networks:
      - database