version: '3'

volumes:
  database:

networks:
  database:

services:
  database:
    image: mysql:8.0
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - database:/var/lib/mysql
    networks:
      - database

  backend:
    image: node:14.17-alpine
    volumes:
      - ./:/home/backend
    working_dir: /home/backend
    command: npx ts-node src/index
    ports:
      - 3000:3000
    depends_on: 
      - database
    networks:
      - database