version: '3'

volumes:
  database:

networks:
  database:

services:
  database:
    image: mysql:8.0
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - database

  app:
    image: node:14.17-alpine
    volumes:
      - ./:/home/app
    working_dir: /home/app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    depends_on: 
      - database
    networks:
      - database